### PR TITLE
feat: add dotnet

### PR DESCRIPTION
**Pull request by fgreinacher**
Needs https://github.com/renovatebot/docker-buildpack/issues/53

### CODE REVIEW

**Comment by viceice** [comment]
I don't think we want this, see renovatebot/docker-renovate#15

**Comment by fgreinacher** [comment]
> I don't think we want this, see [renovatebot/docker-renovate#15](https://github.com/renovatebot/docker-renovate/issues/15)

Ah, wasn't aware that you're planning to get rid of it. We're still using because we don't want the Docker socket mounted in our environment. 

Are there already docs that help us build our custom full image?

**Comment by viceice** [comment]
Not yet, but you can use the full [`Dockerfile`](https://github.com/renovatebot/docker-renovate-full/blob/master/Dockerfile)  as template.

**Comment by viceice** [comment]
You can even remove all tools you don't need to reduce the image size

**Comment by fgreinacher** [comment]
> Not yet, but you can use the full [`Dockerfile`](https://github.com/renovatebot/docker-renovate-full/blob/master/Dockerfile) as template.

OK thanks, that was obviously a very stupid question 🥴 I mean, I even adapted this Dockerfile in here 😁

**Comment by fgreinacher** [comment]
@viceice @rarkins Sorry to open this discussion again, but we would really appreciate if `dotnet` would just be in the image as otherwise we would need to fork this repo with just `dotnet` on top.

**Comment by viceice** [comment]
@fgreinacher Can't you use the slim version? What is the blocker?

**Comment by rarkins** [comment]
@viceice I don't really mind if this already-bloated image becomes yet-more-bloated until the point we deprecate it

**Comment by fgreinacher** [comment]
> @fgreinacher Can't you use the slim version? What is the blocker?

Because I thought the slim version does not have `dotnet` either:

> Run the renovate/renovate:slim Docker Hub image if you only use package managers that don't need third party binaries (e.g. JS, Docker, Nuget, pip)

**Comment by viceice** [comment]
@fgreinacher Looks like we should update the slim image description, the slim image works like the renovate app by default. It starts docker side containers instead of starting global tools. So you could simply start the slim image and mount the docker socket and /tmp  to the renovate container and it should work as expected.


@rarkins Ok, i don't use this image anyways. 🙃

**Comment by fgreinacher** [comment]
> @fgreinacher Looks like we should update the slim image description, the slim image works like the renovate app by default. It starts docker side containers instead of starting global tools. So you could simply start the slim image and mount the docker socket and /tmp  to the renovate container and it should work as expected.
> 

The sidecar approach is unfortunately not feasible for us because we're running Renovate on shared infrastructure where mounting the Docker socket is a no-go security-wise.

> 
> @rarkins Ok, i don't use this image anyways. 🙃 
> 

👍😎

**Pull request merged**
